### ISSUE TITLE
Are you still supporting the app

### ISSUE THREAD

**Issue by andiandi13** [GokulNC/USB_Mass_Storage_Enabler#1]
I've an issue to write about SD mounting and a new mode but I first want to know if you don't have abandoned the app ?

Thanks.

**Comment by GokulNC** [comment]
Lol, it's not abandoned. Just dormant because I've got nothing to change in it, and no one gives a duck about this app ;)
BTW, if you feel you've got any improvements to contribute or bugs to smash, feel free to fix them and send a PR :)

**Comment by andiandi13** [comment]
Glad to hear that, I'm creating an issue then, I'm not a developer though :)
